[DEV_ODC]
label = ODC Dev
host = SL80ORA03-D
port = 1522
sid = ODCDEV
user = GLOBUS_APP
password = App$74335mig
ssl = false

[Test_DB]
label = Test Service
host = gmi-test-rw.globusone.db
port = 1521
service_name = GMIONETEST.wlsokenprddb.wlsokenprdvcn.oraclevcn.com
user = globus_app
password = EvFd_2pDF_hda
ssl = false

#codex resume 019cd859-b9a3-75f0-ad55-b68f96ddbdc3